spring.application.name=rate-limiter
server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Rate Limiter
info.app.version=1.0
info.app.author=Vedant Varma

