version: '3.8'

services:

  redis:
    image: redis:latest
    container_name: redis-rate-limiter
    ports:
      - "6379:6379"

  app:
    image: rate-limiter
    container_name: rate-limiter-app
    ports:
      - "8080:8080"
    depends_on:
      - redis